services:
  backend: &django
    build: .
    container_name: backend
    ports:
      - "8009:8009"
    command: bash -c "poetry run python manage.py collectstatic --no-input && poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8009"
    environment:
      - DOCKER=True
    env_file:
      .env
    volumes:
      - ./app_project/static:/app/app_project/static:rw
    depends_on:
      - db
    restart:
      always

  db:
    image: postgres:16.3
    container_name: db
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      .env
    ports:
      - 5555:5432
    restart: always

  celery-worker:
    <<: *django
    container_name: celery-worker
    ports: []
    command: bash -c "poetry run celery -A celery_config:app worker -l info"

  celery-beat:
    <<: *django
    container_name: celery-beat
    ports: []
    command: bash -c "poetry run celery -A celery_config:app beat -l info"

  flower:
    <<: *django
    container_name: celery-flower
    ports:
      - "5000:5555"
    command: bash -c "poetry run celery -A celery_config:app flower"
    depends_on:
      - celery-worker
      - celery-beat

  redis:
    image: redis:6
    container_name: payment_redis
    env_file:
      - .env
    restart: always

volumes:
  static:
  pg_data:

